import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Roboto } from 'next/font/google';
import Header from "@/Components/Layout/Header";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  preload: true,
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
